function stm32cubemxinstallpath_callback(hDlg, hSrc, paramName)
 
  disp(['*** callback triggered:', sprintf('\n'), ...
        '  You switched popup selection to: ', ...
        slConfigUIGetVal(hDlg, hSrc, paramName)]);